/**
 * Inter-line pacing for sequential dialogue playback.
 *
 * Each line is synthesized in its own request, so the model producing a reply
 * has never seen the question it answers. Playback previously pasted a fixed
 * 400ms between every pair of turns, giving a casual greeting and a weighty
 * philosophical claim identical spacing — a large part of why sequential
 * playback sounds mechanical.
 *
 * Deriving the gap from punctuation and speaker change costs nothing, involves
 * no model, and cannot affect pronunciation.
 */

/** Milliseconds, before speed scaling. */
const GAP = {
  /** Same speaker continuing: one utterance split across lines, not a turn exchange. */
  continuation: 150,
  /** A reply to a question follows promptly. */
  afterQuestion: 250,
  /** Default turn exchange. */
  turn: 400,
  /** A long declarative statement wants room to land. */
  afterLongStatement: 600,
} as const;

/** A line longer than this counts as a "long statement" for pacing purposes. */
const LONG_LINE_CHARS = 60;

const MIN_GAP_MS = 120;
const MAX_GAP_MS = 900;

/**
 * Greek uses U+037E (and, in practice, ASCII `;`) as the question mark.
 * Text imported from Perseus/TLG or generated by the module importer may use
 * either, so both are recognized — as is `?`, for translated or mixed content.
 */
const QUESTION_MARKS = [";", ";", "?"];
const STATEMENT_MARKS = [".", "·", "·", "!"]; // full stop, middle dot, Greek ano teleia, exclamation

function lastMeaningfulChar(text: string): string {
  const trimmed = text.trim();
  return trimmed.length > 0 ? trimmed[trimmed.length - 1] : "";
}

/**
 * How long to pause after `previous` before `next` begins.
 *
 * @param previous  the line that just finished
 * @param next      the line about to play, or null at the end of a sequence
 * @param speed     playback rate; gaps shrink as playback speeds up so fast
 *                  playback does not feel gappy
 */
export function gapAfter(
  previous: { speaker: string; greekText: string },
  next: { speaker: string } | null,
  speed = 1.0
): number {
  if (!next) return 0;

  const final = lastMeaningfulChar(previous.greekText);
  let base: number;

  if (previous.speaker === next.speaker) {
    base = GAP.continuation;
  } else if (QUESTION_MARKS.includes(final)) {
    base = GAP.afterQuestion;
  } else if (STATEMENT_MARKS.includes(final)) {
    base = previous.greekText.trim().length > LONG_LINE_CHARS
      ? GAP.afterLongStatement
      : GAP.turn;
  } else {
    base = GAP.turn;
  }

  const scaled = base / (speed > 0 ? speed : 1);
  return Math.round(Math.min(MAX_GAP_MS, Math.max(MIN_GAP_MS, scaled)));
}

/** Pause before a looped sequence restarts. Longer than any inter-line gap. */
export function loopRestartGap(speed = 1.0): number {
  return Math.round(Math.min(MAX_GAP_MS, Math.max(MIN_GAP_MS, 800 / (speed > 0 ? speed : 1))));
}

/** Pause before a single looped line repeats. */
export function lineRepeatGap(speed = 1.0): number {
  return Math.round(Math.min(MAX_GAP_MS, Math.max(MIN_GAP_MS, 500 / (speed > 0 ? speed : 1))));
}
